In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/netflix-shows/netflix_titles.csv
/kaggle/input/netflix-prize-data/combined_data_3.txt
/kaggle/input/netflix-prize-data/movie_titles.csv
/kaggle/input/netflix-prize-data/combined_data_4.txt
/kaggle/input/netflix-prize-data/combined_data_1.txt
/kaggle/input/netflix-prize-data/README
/kaggle/input/netflix-prize-data/probe.txt
/kaggle/input/netflix-prize-data/combined_data_2.txt
/kaggle/input/netflix-prize-data/qualifying.txt

# Bearbeitung der Daten
In diesem Abschnitt werden die Daten, die Netflix zur Verfügung gestellt hat, in Hinsicht unseres Problems bearbeitet.

## Bearbeitung der Reviews
Hier werden aus den 4 einzelnen `combined_data.csv` Dateien eine große Datei gemacht, die alles enthält.
Da in den originalen Dateien die Filme zu den Reviews so gekennzeichnet wurden, dass vor allen Reviews zu einem Film in einer Zeile die Movie_ID und dann ein ':' geschrieben wurde.

Das wären Reviews zum Film mit der ID 1.
```
1:
1488844,3,2005-09-06
822109,5,2005-05-13
885013,4,2005-10-19
```

Da Pandas nicht gut damit umgehen kann, erstellen wir eine neue Datei, die als extra Spalte neben jeder Review auch die ID des Films angibt. Diese speichern wir unter `input/combined_data.csv` ab.

In [2]:
def extractData():
    # Erstelle File und schreibe header
    with open(f"combined_data.csv", 'w') as file:
        file.write('Movie_ID,User_ID,Ratings,ReleaseDate\n')

    # Öffne das selbe File in append mode und füge neue Daten hinzu 
    with open(f"combined_data.csv", 'a') as out_file:
        for i in range(1, 5):
            with open(f"../input/netflix-prize-data/combined_data_{i}.txt", 'r') as in_file:
                lines = in_file.read().split('\n')

            new, movie_id = [], ''
            for line in lines:
                if line == '':
                    continue
                if ':' in line:
                    movie_id = line.replace(':', '')
                    continue
                new.append(f"{movie_id},{line}")

            out_file.write('\n'.join(new) + '\n')

## Bearbeitung der Filme
Hier wird die Datei, welche Details zu den Filmen enthält von einem csv manuell in ein tsv umgewandelt, da die Filmnamen ',' enthalten und der pandas Tokenizer das nicht verarbeiten kann. Zudem ändern wir das character encoding zu utf-8.

In [3]:
def formatMovieData():
    with open('../input/netflix-prize-data/movie_titles.csv', 'r', encoding='ISO-8859-1') as file:
        lines = file.read().split('\n')

    new = list(map(lambda x: x.replace(',', '\t', 2), lines))

    with open('movie_titles.tsv', 'w', encoding='UTF-8') as file:
        file.write('Movie_ID\tYear\tTitle\n' + '\n'.join(new))

In [4]:
# Dauer ~ 3 min
#extractData()
#formatMovieData()

# Machine Learning

In [5]:
#df_movies = pd.read_csv('movie_titles.tsv', sep='\t', index_col='Movie_ID')
#df_movies.head()
#wir haben ingesamt 17 770 Filme

In [6]:
#df_movies.loc[21]

In [7]:
#df_movies[df_movies['Year'].isna()]

In [8]:
#df_ratings = pd.read_csv('combined_data.csv', index_col='Movie_ID')
#df_ratings.head()

In [9]:
#df_ratings.loc[756]

In [10]:
#for movie_id in df_movies.index:
#    print(f"Movie: {df_movies.loc[movie_id]['Title']}\nAverage Rating {sum(df_ratings.loc[movie_id]['Ratings'])/(df_ratings.loc[movie_id].shape[0]):.1f}\n")

#    if movie_id > 10:
#        break

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [12]:
#df_movies.head()

In [13]:
#df_movies['Rating'] = ''
#df_movies['NumRating'] = ''
#df_movies.head()

In [14]:
#for movie_id in df_movies.index:
#    num_ratings = (df_ratings.loc[movie_id].shape[0])
#    df_movies.at[movie_id ,'NumRating'] = num_ratings
#    df_movies.at[movie_id, 'Rating'] = sum(df_ratings.loc[movie_id]['Ratings'])/num_ratings

In [15]:
#df_movies.head()

In [16]:
#df_metadata = pd.read_csv('../input/netflix-shows/netflix_titles.csv',usecols = ['title', 'type', 'description', 'listed_in'], index_col='title').dropna()
#df_metadata = df_metadata[df_metadata['type'] == 'Movie'].drop('type', axis=1)
#df_metadata.head()

In [17]:
#df_metadata = pd.merge(df_movies, df_metadata, left_on = 'Title', right_on = 'title').head()

In [18]:
#df_metadata.shape

In [19]:
#df_metadata.set_index('Title', inplace = True)
#df_metadata.shape

In [20]:
#df_metadata.head()

In [21]:
#genres = dict()
#for listed_in in df_metadata['listed_in']:
#    for genre in listed_in.split(','):
#        if genre in genres:
#            genres[genre] += 1
#        else:
#            genres[genre] = 1
#genres

In [22]:
# Genres aus df_metadata
#g = df_metadata['listed_in'].str.split(',').apply(pd.Series, 1).stack()
#g.index = g.index.droplevel(-1)  #gleice Indizes wie bei df_metadata
#g.index = g.rename(lambda x: x)  #dass wir keinen Unterschied wegen drop haben

#Wir wollen dann alle duplicate löschen
#g = g.drop_duplicates()

#tf-idf matrix für Textvergleich
#tfidf = TfidfVectorizer(stop_words = list(g))
#tfidf_matrix = tfidf.fit_transform(df_metadata['listed_in'].dropna())

In [23]:
#from sklearn.feature_extraction.text import TfidfVectorizer
#removing stopwords
#tfidf = TfidfVectorizer(stop_words='english')

#Wir vertauschen NaN mit empty string
#df_metadata['descrition'] = df_metadata['description'].fillna('')

#Konstruieren gebrauchte TF-IDF matrix by fitting and transforming the data
#tfidf_matrix = tfidf.fit_transform(df_metadata['description'])

#Output the shape of tfidf_matrix
#tfidf_matrix.shape

In [24]:
#from sklearn.metrics.pairwise import linear_kernel
# Compute the cosine similarity matrix
#cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

#indices = pd.Series(df_movies.index, index=df_metadata['title']).drop_duplicates()

In [25]:
#tf-idf matrix für Textvergleich
#tfidf = TfidfVectorizer(stop_words = list(g))
#tfidf_matrix = tfidf.fit_transform(df_metadata['listed_in'].dropna())


# Berechne cosine similarity matrix
#cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
#indices = pd.Series(df_metadata.index, index=df_metadata['Title'])

#def get_recommendations(title, cosine_sim=cosine_sim):
#    idx = indices[title]

    # pairwise similarity scores aller Filme mit eingegebenen Film
#    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sortiert nach similarity scores
#    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Scores der 15 ähnlichsten Filmen
#    sim_scores = sim_scores[1:16]

    # Film indices
#    movie_indices = [i[0] for i in sim_scores]

    # Return top 15 ähnlichsten Filme
#    return df_metadata.iloc[movie_indices]

In [26]:
#get_recommendations('New York Minute')

# NEU

In [27]:
df_metadata = pd.read_csv('../input/netflix-shows/netflix_titles.csv', usecols=['title', 'type','release_year', 'rating', 'listed_in', 'description']).dropna()

In [28]:
print(df_metadata.shape)
df_metadata.head()

(8803, 6)

,type,title,release_year,rating,listed_in,description
0,Movie,Dick Johnson Is Dead,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm..."
1,TV Show,Blood & Water,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,TV Show,Ganglands,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,TV Show,Jailbirds New Orleans,2021,TV-MA,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,TV Show,Kota Factory,2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [29]:
#df_metadata = df_metadata[df_metadata['type'] == 'Movie'].drop('type', axis=1)

In [30]:
print(df_metadata.shape)
df_metadata['Index'] = range(df_metadata.shape[0])
df_metadata.set_index('Index', inplace=True)
df_metadata.head()

(8803, 6)

,type,title,release_year,rating,listed_in,description
Index,,,,,,
0,Movie,Dick Johnson Is Dead,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm..."
1,TV Show,Blood & Water,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,TV Show,Ganglands,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,TV Show,Jailbirds New Orleans,2021,TV-MA,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,TV Show,Kota Factory,2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
#removing stopwords
tfidf = TfidfVectorizer(stop_words='english')

#Replace NaN with an empty string
df_metadata['description'] = df_metadata['description'].fillna('')

#Construct the required TF-IDF matrix by fitting and transforming the data
tfidf_matrix = tfidf.fit_transform(df_metadata['description'])

#Output the shape of tfidf_matrix
tfidf_matrix.shape

(8803, 18891)

In [32]:
# Import linear_kernel
from sklearn.metrics.pairwise import linear_kernel
# Compute the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

indices = pd.Series(df_metadata.index, index=df_metadata['title']).drop_duplicates()

In [33]:
def get_recommendations(title, cosine_sim=cosine_sim):
    idx = indices[title]

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[1:11]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return df_metadata.iloc[movie_indices]

In [34]:
df_metadata[df_metadata['title'].apply(lambda x: 'matrix' in x.lower())].head()

,type,title,release_year,rating,listed_in,description
Index,,,,,,
8410,Movie,The Matrix,1999,R,"Action & Adventure, Sci-Fi & Fantasy",A computer hacker learns that what most people...
8411,Movie,The Matrix Reloaded,2003,R,"Action & Adventure, Sci-Fi & Fantasy","The crew must protect Zion, the last outpost s..."
8412,Movie,The Matrix Revolutions,2003,R,"Action & Adventure, Sci-Fi & Fantasy",The final installment in the Matrix trilogy fi...

In [1]:
get_recommendations('9')

NameError: name 'get_recommendations' is not defined

In [36]:
get_recommendations('My Little Pony Equestria Girls: Rainbow Rocks')

,type,title,release_year,rating,listed_in,description
Index,,,,,,
7537,Movie,My Little Pony Equestria Girls: Friendship Games,2015,TV-Y,"Children & Family Movies, Comedies","Rainbow Dash, Applejack and friends compete ag..."
4590,Movie,My Little Pony Equestria Girls: Rollercoaster ...,2018,TV-Y,Children & Family Movies,"Rarity gets a summer job at Equestria Land, ma..."
4674,TV Show,The Comedy Lineup,2018,TV-MA,"Stand-Up Comedy & Talk Shows, TV Comedies",A diverse group of up-and-coming comedians per...
5237,TV Show,Equestria Girls: Tales of Canterlot High,2017,TV-Y7,"Kids' TV, TV Comedies","In an alternate universe Equestria, the ponies..."
2440,Movie,True: Rainbow Rescue,2020,TV-Y,Children & Family Movies,True and Bartleby travel to the other side of ...
8774,Movie,Yes or No 2,2012,TV-PG,"International Movies, LGBTQ Movies, Romantic M...","No longer university girls, Kim and Pie face n..."
8773,Movie,Yes or No,2010,TV-PG,"International Movies, LGBTQ Movies, Romantic M...",Traditional girl Pie is initially uncomfortabl...
3079,TV Show,ARASHI's Diary -Voyage-,2019,TV-PG,"Docuseries, International TV Shows","Twenty years after their debut, join the belov..."
2612,Movie,Beynelmilel,2006,TV-MA,"Comedies, Dramas, International Movies",When a local musician and his band are forced ...
8775,Movie,Yes or No 2.5,2015,TV-PG,"International Movies, LGBTQ Movies, Romantic M...",Roommates Wine and Pie find their lives turned...

In [37]:
df_metadata['meta'] = ''
for idx, row in df_metadata.iterrows():
    df_metadata.at[idx, 'meta'] = row['title'] + ' | ' + row['listed_in'] + ' | ' + row['description']

In [38]:
df_metadata.head()

,type,title,release_year,rating,listed_in,description,meta
Index,,,,,,,
0,Movie,Dick Johnson Is Dead,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm...",Dick Johnson Is Dead | Documentaries | As her ...
1,TV Show,Blood & Water,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...","Blood & Water | International TV Shows, TV Dra..."
2,TV Show,Ganglands,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,"Ganglands | Crime TV Shows, International TV S..."
3,TV Show,Jailbirds New Orleans,2021,TV-MA,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...","Jailbirds New Orleans | Docuseries, Reality TV..."
4,TV Show,Kota Factory,2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,"Kota Factory | International TV Shows, Romanti..."

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer
#removing stopwords
tfidf = TfidfVectorizer(stop_words='english')

#Replace NaN with an empty string
df_metadata['meta'] = df_metadata['meta'].fillna('')

#Construct the required TF-IDF matrix by fitting and transforming the data
tfidf_matrix = tfidf.fit_transform(df_metadata['meta'])

#Output the shape of tfidf_matrix
tfidf_matrix.shape

(8803, 22349)

In [40]:
# wir importieren linear_kelner
from sklearn.metrics.pairwise import linear_kernel
# berechnen cosine similarity
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

indices = pd.Series(df_metadata.index, index=df_metadata['title']).drop_duplicates()

In [41]:
def get_recommendations(title, cosine_sim=cosine_sim):
    idx = indices[title]

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[1:11]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return df_metadata.iloc[movie_indices]

In [42]:
df_metadata[df_metadata['title'].apply(lambda x: "platform".lower() in x.lower())].head(5)

,type,title,release_year,rating,listed_in,description,meta
Index,,,,,,,
820,TV Show,The Platform,2021,TV-14,"International TV Shows, TV Dramas, TV Mysteries","A programming genius builds a fact-finding, tr...","The Platform | International TV Shows, TV Dram..."

In [44]:
get_recommendations("Terminator 3")

,type,title,release_year,rating,listed_in,description,meta
Index,,,,,,,
8411,Movie,The Matrix Reloaded,2003,R,"Action & Adventure, Sci-Fi & Fantasy","The crew must protect Zion, the last outpost s...","The Matrix Reloaded | Action & Adventure, Sci-..."
8412,Movie,The Matrix Revolutions,2003,R,"Action & Adventure, Sci-Fi & Fantasy",The final installment in the Matrix trilogy fi...,"The Matrix Revolutions | Action & Adventure, S..."
5958,Movie,9,2009,PG-13,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...","9 | Action & Adventure, Independent Movies, Sc..."
5474,Movie,Arès,2016,TV-MA,"Action & Adventure, International Movies, Sci-...",A futuristic France tries to keep its people f...,"Arès | Action & Adventure, International Movie..."
2227,TV Show,Cursed,2020,TV-MA,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ...",Armed with mysterious powers and a legendary s...,"Cursed | TV Action & Adventure, TV Dramas, TV ..."
2526,TV Show,She-Ra and the Princesses of Power,2020,TV-Y7,"Kids' TV, TV Action & Adventure, TV Sci-Fi & F...",Soldier Adora finds a magic sword – and her id...,"She-Ra and the Princesses of Power | Kids' TV,..."
8162,Movie,Terminator 3: Rise of the Machines,2003,R,"Action & Adventure, Sci-Fi & Fantasy",Ten years after John Connor saved Earth from J...,Terminator 3: Rise of the Machines | Action & ...
7197,Movie,Kill Command,2016,TV-MA,"Action & Adventure, Independent Movies, Sci-Fi...","On a remote island, elite soldiers discover th...","Kill Command | Action & Adventure, Independent..."
8316,Movie,The Girl with the Dragon Tattoo,2011,R,"Dramas, Thrillers",When a young computer hacker is tasked with in...,"The Girl with the Dragon Tattoo | Dramas, Thri..."
6001,Movie,2307: Winter's Dream,2016,TV-MA,"Action & Adventure, Independent Movies, Sci-Fi...",In the frozen tundra of a futuristic Arizona w...,"2307: Winter's Dream | Action & Adventure, Ind..."